services:
  - type: web
    name: doodle-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/app.py
    envVars:
      - key: FLASK_ENV
        value: production
